from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('companies/', views.company_list, name='company_list'),
    path('companies/add/', views.add_company, name='add_company'),
    path('companies/<int:pk>/select/', views.select_company, name='select_company'),
    path('companies/open-sample/', views.open_sample_company, name='open_sample_company'),
    path('companies/save/', views.save_company, name='save_company'),
    path('companies/copy/', views.copy_company, name='copy_company'),
    path('companies/backup/', views.backup_company, name='backup_company'),
    path('transactions/', views.transaction_list, name='transaction_list'),
    path('transactions/add/', views.add_transaction, name='add_transaction'),
    path('transactions/<int:pk>/edit/', views.edit_transaction, name='edit_transaction'),
    path('pnl/', views.profit_and_loss, name='pnl'),
    path('balance-sheet/', views.balance_sheet, name='balance_sheet'),
    path('trial-balance/', views.trial_balance, name='trial_balance'),
    path('coa/', views.chart_of_accounts, name='coa_list'),
    path('coa/add/', views.add_account, name='add_account'),
    path('coa/<int:pk>/edit/', views.edit_account, name='edit_account'),
    path('lists/vendors/', views.vendor_list, name='vendor_list'),
    path('lists/vendors/add/', views.add_vendor, name='add_vendor'),
    path('lists/vendors/<int:pk>/edit/', views.edit_vendor, name='edit_vendor'),
    path('lists/classes/', views.class_list, name='class_list'),
    path('llc/add/', views.add_llc, name='add_llc'),
    path('llc/<int:pk>/edit/', views.edit_llc, name='edit_llc'),
    path('property/add/', views.add_property, name='add_property'),
    path('property/<int:pk>/edit/', views.edit_property, name='edit_property'),
    path('class/add/', views.add_class, name='add_class'),
    path('class/<int:pk>/edit/', views.edit_class, name='edit_class'),
    path('import/', views.import_file, name='import_file'),
    path('import/categorize/', views.categorize_import, name='categorize_import'),
    path('import/process/', views.process_import, name='process_import'),
    path('reconcile/', views.reconcile, name='reconcile'),
    path('close/', views.close_books_view, name='close_books'),
    path('journal/add/', views.add_journal_entry, name='add_journal_entry'),
    path('ajax/add-account/', views.add_account_ajax, name='add_account_ajax'),
]
