# Generated by Django 6.0.5 on 2026-05-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="name",
        ),
    ]
