# Generated by Django 6.0.5 on 2026-05-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="accounting.company",
            ),
        ),
        migrations.AddField(
            model_name="accountingclass",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="accounting.company",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="accounting.company",
            ),
        ),
        migrations.AddField(
            model_name="llc",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llcs",
                to="accounting.company",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.company",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendors",
                to="accounting.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="accountingclass",
            unique_together={("company", "name", "parent")},
        ),
    ]
