# Generated by Django 6.0.5 on 2026-05-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="db_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
